# This script is used by the Travis-CI (continuous integration) testing
# framework to run SimulationCrafts tests with every GitHub push or pull-request.
language: cpp

branches:
  only:
    - bfa-dev

sudo: false
# Enable Trusty (Ubuntu 14.04 LTS)
dist: trusty

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-5

install:
  # Build SimulationCraft
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make CXX=g++-5 OPENSSL=1 optimized; fi
